name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Set TAG env
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Build
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o stormy${{ matrix.goos == 'windows' && '.exe' || '' }}
          tar -czvf dist/stormy-${TAG}-${{ matrix.goarch }}-${{ matrix.goos }}.tar.gz stormy${{ matrix.goos == 'windows' && '.exe' || '' }} README.md LICENSE
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
